# Generated by Django 5.1 on 2024-08-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='Extinction',
            field=models.DateTimeField(),
        ),
    ]
