# Generated by Django 5.1 on 2024-08-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_animal_extinction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='Extinction',
            field=models.CharField(max_length=100),
        ),
    ]
