# Generated by Django 5.1 on 2024-08-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_animal_extinction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='Extinction',
            new_name='extinction',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='Power',
            new_name='power',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='Weight',
            new_name='weight',
        ),
    ]
